---
# tasks file for secure_time_sync
- name: Get secure-time-sync
  ansible.builtin.get_url:
    dest: /usr/local/bin/secure-time-sync
    url: https://raw.githubusercontent.com/szorfein/secure-time-sync/main/secure-time-sync.sh
    checksum: sha256:9dde9b9cba77930d66d1a82651c377b5b7ea2bbc40f02e3490e575bac3dc5a96
    mode: 0755

- name: Dependencies
  ansible.builtin.package:
    name: curl
    state: present

- name: Add Tor
  ansible.builtin.package:
    name: tor
    state: present
  notify:
    - Start Tor
  when: use_tor | bool

- name: Adding systemd service
  ansible.builtin.template:
    src: systemd.service.j2
    dest: /usr/lib/systemd/system/secure-time-sync.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Enable Sts
  when: ansible_service_mgr == 'systemd'

- name: Adding runit service
  ansible.builtin.copy:
    src: secure-time-sync
    dest: /etc/sv/
    directory_mode: yes
    owner: root
    group: root
    mode: '0755'
  notify:
    - Enable Sts
  when: ansible_service_mgr == 'runit'

- name: Config Tor
  ansible.builtin.lineinfile:
    path: /etc/tor/torrc
    regexp: '^SOCKSPort 9050'
    line: 'SOCKSPort 9050'
    state: present
    validate: 'tor --verify-config -f %s'
  notify:
    - Restart Tor
  when: use_tor | bool

- name: Enable service with Tor
  ansible.builtin.template:
    src: systemd-with-tor.service.j2
    dest: /usr/lib/systemd/system/secure-time-sync-with-tor.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Enable Sts with Tor
  when: ansible_service_mgr == 'systemd' and use_tor | bool

- name: Cronie
  ansible.builtin.package:
    name: cronie
    state: present
  notify:
    - Enable Cronie
  when: ansible_service_mgr == 'runit' and use_tor | bool

- name: Enable cron job
  ansible.builtin.cron:
    name: 'Synchronise time with Tor.'
    minute: '5'
    job: '/usr/local/bin/secure-time-sync --use-tor'
  when: ansible_service_mgr == 'runit' and use_tor | bool

- name: Disable cron job
  ansible.builtin.cron:
    name: 'Synchronise time with Tor.'
    job: '/usr/local/bin/secure-time-sync --use-tor'
    state: absent
  when: ansible_service_mgr == 'runit' and not use_tor | bool

- name: Apparmor
  import_tasks: apparmor.yml
  when: ansible_apparmor.status == 'enabled'

- name: Disable systemd NTP protocol
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - systemd-timesyncd
  ignore_errors: true
  when: ansible_service_mgr == 'systemd'
