---
- hosts: hardened
  collections:
    - szorfein.hardening
  become: true
  roles:
    - { role: szorfein.hardening.os, os_modprobe_remove_bluetooth: true }
    #- { role: szorfein.hardening.ssh, allowed_users: [ ansible ] }

- hosts: privacy
    - szorfein.privacy
  become: true
  roles:
    - { role: szorfein.privacy.os, os_wifi_client: iwd }

- hosts: test
  become: true
  collections:
    - szorfein.privacy
  roles:
    - { role: szorfein.hardening.os, os_modprobe_remove_bluetooth: true }
      #- { role: szorfein.privacy.os, os_wifi_client: iwd }

