---
- hosts: hardened
  become: true
  roles:
    - { role: secure_shell, allowed_users: [ ansible ] }
    - hardened
    - { role: kernel_modules, remove_bluetooth: true }
    - cmdline
    - sysctl

- hosts: privacy
  become: true
  roles:
    - privacy
    - secure_time_sync
    - { role: mac_spoof, wifi_client: iwd }

- hosts: test
  become: true
  roles:
    - packages
