---
- hosts: hardened
  collections:
    - szorfein.hardening
  become: true
  roles:
    #- { role: szorfein.hardening.ssh, allowed_users: [ ansible ] }
    - { role: szorfein.hardening.os, os_modprobe_remove_bluetooth: true }

- hosts: privacy
    - szorfein.privacy
  become: true
  roles:
    - secure_time_sync
    - { role: mac_spoof, wifi_client: iwd }
    - { role: szorfein.privacy.os, os_wifi_client: iwd }

- hosts: test
  become: true
  collections:
    - szorfein.privacy
  roles:
    - szorfein.privacy.os

