---
- hosts: hardened
  become: true
  roles:
    - { role: secure_shell, allowed_users: [ ansible ] }
    - hardened
    - { role: kernel_modules, remove_bluetooth: true }
    - cmdline
    - sysctl

- hosts: privacy
  gather_facts: false
  become: true
  roles:
    - privacy
    - secure_time_sync

- hosts: test
  become: true
  roles:
