---
- hosts: hardened
  become: true
  roles:
    - hardened
    - sysctl
    - cmdline

- hosts: privacy
  gather_facts: false
  become: true
  roles:
    - privacy

- hosts: test
  become: true
  roles:
