---
- hosts: hardened
  become: true
  roles:
    - hardened
    - sysctl

- hosts: privacy
  gather_facts: false
  become: true
  roles:
    - privacy
    - secure_time_sync

- hosts: test
  become: true
  roles:
