---
- hosts: hardened
  become: true
  roles:
    - { role: secure_shell, allowed_users: [ ansible ] }
    - hardened
    - { role: kernel_modules, remove_bluetooth: true }
    - sysctl
    - cmdline

- hosts: privacy
  gather_facts: false
  become: true
  roles:
    - privacy

- hosts: test
  become: true
  roles:
