---
- hosts: hardened
  become: true
  roles:
    - hardened
    - sysctl

- hosts: privacy
  gather_facts: false
  become: true
  roles:
    - privacy

- hosts: test
  become: true
  roles:
    - { role: kernel_modules, remove_bluetooth: true }
