---
- name: adding pkgs
  ansible.builtin.apt:
    pkg:
      - libpam-tmpdir
      - apt-listbugs
      - needrestart
      - debsecan
      - debsums
      #  - fail2ban
    state: present
    update_cache: true
