---
- name: Adding more entropy
  import_tasks: entropy.yml

- name: Fixing permissions
  import_tasks: permission.yml

- name: Hidepid
  import_tasks: hidepid.yml

- name: Coredump
  import_tasks: coredump.yml
