---
- name: Checking /etc/machine-id
  ansible.builtin.stat:
    path: /etc/machine-id
  register: p

- name: Changing the machine-id for /etc/machine-id
  copy:
    dest: /etc/machine-id
    content: "b08dfa6083e7567a1921a715000001fb\n"
  when: p.stat.exists

- name: Checking /var/lib/dbus/machine-id
  ansible.builtin.stat:
    path: /var/lib/dbus/machine-id
  register: p

- name: Changing the machine-id for /var/lib/dbus/machine-id
  copy:
    dest: /var/lib/dbus/machine-id
    content: "b08dfa6083e7567a1921a715000001fb\n"
  when: p.stat.exists

