---
- name: Reload systemd
  ansible.builtin.shell: 'systemctl daemon-reload'
  when: ansible_service_mgr == 'systemd'

- name: Start Tor
  ansible.builtin.service:
    name: tor
    state: started
    enabled: true

- name: Enable Cronie
  ansible.builtin.service:
    name: cronie
    state: started
    enabled: true

- name: Enable Sts
  ansible.builtin.service:
    name: secure-time-sync
    state: started
    enabled: true

- name: Enable Sts with Tor
  ansible.builtin.service:
    name: secure-time-sync-with-tor
    state: started
    enabled: true

- name: Restart Tor
  ansible.builtin.service:
    name: tor
    state: restarted
