---
- name: Start Entropy Service
  ansible.builtin.service:
    name: '{{ service_name }}'
    state: started
    enabled: true
  when: service_name is defined

- name: Load Entropy Module
  ansible.builtin.template:
    src: entropy_mod.j2
    dest: /usr/lib/modules-load.d/jitterentropy.conf
  when: entropy_module is defined
