---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/include_vars_module.html
- name: Load variable file for {{ ansible_os_family }}
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_os_family }}.yml'
        - main.yml
      paths:
        - 'vars'

- name: Installing macchanger
  ansible.builtin.package:
    name: macchanger
    state: present

- ansible.builtin.stat:
    path: /etc/iwd
  register: p

- name: Configuring iwd
  ansible.builtin.template:
    src: iwd.conf.j2
    dest: /etc/iwd/main.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart iwd
  when: p.stat.isdir is defined and p.stat.isdir

- ansible.builtin.stat:
    path: /etc/wpa_supplicant
  register: p

- name: wpa_supplicant
  include_tasks: wpa_supplicant.yml
  when: p.stat.isdir is defined and p.stat.isdir and interface.startswith("wl")
  loop: '{{ ansible_facts.interfaces }}'
  loop_control:
    loop_var: interface # rename loop default name 'item' by 'interface'

- ansible.builtin.stat:
    path: /etc/udev/rules.d
  register: p

- name: Installing udev rules > {{ udev_file_name }}
  ansible.builtin.template:
    src: udev.rules.j2
    dest: "/etc/udev/rules.d/{{ udev_file_name }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart udev
  when: p.stat.isdir is defined and p.stat.isdir
