---
# https://wiki.debian.org/Microcode
- name: Add microcode repository.
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - deb http://deb.debian.org/debian bullseye main contrib non-free
    - deb http://security.debian.org/debian-security bullseye-security main contrib non-free
    - deb http://deb.debian.org/debian bullseye-updates main contrib non-free
